site_name: Malware Tracker
theme: 'readthedocs'

pages:
- Home: 'index.md'
- Guide:
  - 'Demo Installation': 'guide/demoinstall.md'
  - 'Scripts': 'guide/scripts.md'
  - 'Configuration': 'guide/configuration.md'
